apiVersion: v1
kind: Service
metadata:
  name: job-sathi-back
spec:
  type: NodePort
  selector:
    app: job-sathi-back
  ports:
    - protocol: TCP
      port: 9001        # backend port (tomcat)
      targetPort: 9001
      nodePort: 30001 
