server.port=9001
spring.application.name=job-sathi
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#ai.openai.model=meta-llama/Llama-4-Scout-17B-16E-Instruct
ai.openai.model=llama-3.1-8b-instant
ai.openai.api-key=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

jwt.secret=job-sathi-secret-key-is-a-very-unique-seceret-key-so-ha
jwt.expiration=60000